import { Project, Task } from '../types';

export interface PersonHoursReport {
  email: string;
  name: string;
  totalHours: number;
  taskCount: number;
  tasks: Array<{
    taskName: string;
    projectName: string;
    hours: number;
    timeEntries: Array<{
      date: Date;
      hours: number;
    }>;
  }>;
}

export const generateHoursReports = (projects: Project[]): PersonHoursReport[] => {
  const emailMap = new Map<string, PersonHoursReport>();
  const debugInfo: string[] = [];

  projects.forEach((project) => {
    project.tasks.forEach((task) => {
      if (!task.assignee || task.assignee.trim() === '') {
        debugInfo.push(`Task "${task.name}" skipped: No assignee`);
        return;
      }

      const email = task.assignee.trim().toLowerCase();
      
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      if (!emailRegex.test(email)) {
        debugInfo.push(`Task "${task.name}" skipped: Invalid email format "${email}"`);
        return;
      }

      const timeEntries = task.timeEntries || [];
      
      if (timeEntries.length === 0) {
        debugInfo.push(`Task "${task.name}" skipped: No time entries`);
        return;
      }

      const totalTaskHours = timeEntries.reduce((sum, entry) => {
        const hours = typeof entry.hours === 'number' ? entry.hours : 0;
        return sum + hours;
      }, 0);
      
      if (totalTaskHours === 0) {
        debugInfo.push(`Task "${task.name}" skipped: Total hours is 0 (time entries: ${timeEntries.length})`);
        return;
      }

      if (!emailMap.has(email)) {
        emailMap.set(email, {
          email,
          name: email.split('@')[0],
          totalHours: 0,
          taskCount: 0,
          tasks: [],
        });
      }

      const report = emailMap.get(email)!;
      report.totalHours += totalTaskHours;
      report.taskCount += 1;
      report.tasks.push({
        taskName: task.name,
        projectName: project.name,
        hours: totalTaskHours,
        timeEntries: timeEntries.map(entry => ({
          date: entry.date instanceof Date ? entry.date : new Date(entry.date),
          hours: typeof entry.hours === 'number' ? entry.hours : 0,
        })),
      });

      debugInfo.push(`Task "${task.name}" added: ${totalTaskHours}h for ${email}`);
    });
  });

  if (emailMap.size === 0 && debugInfo.length > 0) {
    console.log('Report generation debug info:', debugInfo);
  }

  return Array.from(emailMap.values()).sort((a, b) => b.totalHours - a.totalHours);
};

export const formatReportForEmail = (report: PersonHoursReport): string => {
  const tasksList = report.tasks
    .map((task) => {
      const timeEntryList = task.timeEntries
        .map(entry => `    ${entry.date.toLocaleDateString()}: ${entry.hours}h`)
        .join('\n');
      return `  • ${task.taskName} (${task.projectName}): ${task.hours}h\n${timeEntryList}`;
    })
    .join('\n');

  return `
Hours Report for ${report.name}

Total Hours Worked: ${report.totalHours}h
Number of Tasks: ${report.taskCount}

Task Breakdown:
${tasksList}

---
Generated by Time Management System
`;
};

export const formatReportHTML = (report: PersonHoursReport): string => {
  const tasksList = report.tasks
    .map((task) => {
      const timeEntryRows = task.timeEntries
        .map(entry => `
          <tr style="background: #f9fafb;">
            <td style="padding: 8px; border-bottom: 1px solid #e5e7eb;"></td>
            <td style="padding: 8px; border-bottom: 1px solid #e5e7eb;"></td>
            <td style="padding: 8px; border-bottom: 1px solid #e5e7eb; text-align: right;">${entry.hours}h</td>
            <td style="padding: 8px; border-bottom: 1px solid #e5e7eb; font-size: 0.875rem; color: #6b7280;">${entry.date.toLocaleDateString()}</td>
          </tr>
        `)
        .join('');
      
      return `
            <tr>
              <td style="padding: 8px; border-bottom: 1px solid #e5e7eb; font-weight: 500;">${task.taskName}</td>
              <td style="padding: 8px; border-bottom: 1px solid #e5e7eb;">${task.projectName}</td>
              <td style="padding: 8px; border-bottom: 1px solid #e5e7eb; text-align: right; font-weight: 600;">${task.hours}h</td>
              <td style="padding: 8px; border-bottom: 1px solid #e5e7eb;">Total</td>
            </tr>
            ${timeEntryRows}
          `;
    })
    .join('');

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: Arial, sans-serif; color: #374151; }
        .container { max-width: 800px; margin: 0 auto; padding: 20px; }
        h1 { color: #f97316; }
        .summary { background: #fff7ed; padding: 20px; border-radius: 8px; margin: 20px 0; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th { background: #f97316; color: white; padding: 12px; text-align: left; }
        .total { font-size: 1.5em; font-weight: bold; color: #f97316; }
      </style>
    </head>
    <body>
      <div class="container">
        <h1>Hours Report</h1>
        <div class="summary">
          <p><strong>Name:</strong> ${report.name}</p>
          <p><strong>Email:</strong> ${report.email}</p>
          <p class="total">Total Hours: ${report.totalHours}h</p>
          <p>Number of Tasks: ${report.taskCount}</p>
        </div>
        <h2>Task Breakdown</h2>
             <table>
               <thead>
                 <tr>
                   <th>Task Name</th>
                   <th>Project</th>
                   <th>Hours</th>
                   <th>Date</th>
                 </tr>
               </thead>
               <tbody>
                 ${tasksList}
               </tbody>
             </table>
        <p style="margin-top: 30px; color: #6b7280; font-size: 0.875rem;">
          Generated by Time Management System
        </p>
      </div>
    </body>
    </html>
  `;
};

