import { Project, Task } from '../types';

export interface PersonHoursReport {
  email: string;
  name: string;
  totalHours: number;
  taskCount: number;
  tasks: Array<{
    taskName: string;
    projectName: string;
    hours: number;
    startDate: Date;
    endDate: Date;
  }>;
}

export const generateHoursReports = (projects: Project[]): PersonHoursReport[] => {
  const emailMap = new Map<string, PersonHoursReport>();

  // Collect all tasks with assignees (emails) from all projects
  projects.forEach((project) => {
    project.tasks.forEach((task) => {
      if (task.assignee && task.assignee.trim() !== '') {
        const email = task.assignee.trim().toLowerCase();
        
        // Validate email format
        const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
        if (!emailRegex.test(email)) {
          return; // Skip invalid emails
        }

        if (!emailMap.has(email)) {
          emailMap.set(email, {
            email,
            name: email.split('@')[0], // Use email username as default name
            totalHours: 0,
            taskCount: 0,
            tasks: [],
          });
        }

        const report = emailMap.get(email)!;
        report.totalHours += task.hoursSpent;
        report.taskCount += 1;
        report.tasks.push({
          taskName: task.name,
          projectName: project.name,
          hours: task.hoursSpent,
          startDate: task.startDate,
          endDate: task.endDate,
        });
      }
    });
  });

  // Convert to array and sort by total hours (descending)
  return Array.from(emailMap.values()).sort((a, b) => b.totalHours - a.totalHours);
};

export const formatReportForEmail = (report: PersonHoursReport): string => {
  const tasksList = report.tasks
    .map((task) => {
      const dateRange = `${task.startDate.toLocaleDateString()} - ${task.endDate.toLocaleDateString()}`;
      return `  • ${task.taskName} (${task.projectName}): ${task.hours}h (${dateRange})`;
    })
    .join('\n');

  return `
Hours Report for ${report.name}

Total Hours Worked: ${report.totalHours}h
Number of Tasks: ${report.taskCount}

Task Breakdown:
${tasksList}

---
Generated by Time Management System
`;
};

export const formatReportHTML = (report: PersonHoursReport): string => {
  const tasksList = report.tasks
    .map((task) => {
      const dateRange = `${task.startDate.toLocaleDateString()} - ${task.endDate.toLocaleDateString()}`;
      return `
        <tr>
          <td style="padding: 8px; border-bottom: 1px solid #e5e7eb;">${task.taskName}</td>
          <td style="padding: 8px; border-bottom: 1px solid #e5e7eb;">${task.projectName}</td>
          <td style="padding: 8px; border-bottom: 1px solid #e5e7eb; text-align: right;">${task.hours}h</td>
          <td style="padding: 8px; border-bottom: 1px solid #e5e7eb;">${dateRange}</td>
        </tr>
      `;
    })
    .join('');

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: Arial, sans-serif; color: #374151; }
        .container { max-width: 800px; margin: 0 auto; padding: 20px; }
        h1 { color: #f97316; }
        .summary { background: #fff7ed; padding: 20px; border-radius: 8px; margin: 20px 0; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th { background: #f97316; color: white; padding: 12px; text-align: left; }
        .total { font-size: 1.5em; font-weight: bold; color: #f97316; }
      </style>
    </head>
    <body>
      <div class="container">
        <h1>Hours Report</h1>
        <div class="summary">
          <p><strong>Name:</strong> ${report.name}</p>
          <p><strong>Email:</strong> ${report.email}</p>
          <p class="total">Total Hours: ${report.totalHours}h</p>
          <p>Number of Tasks: ${report.taskCount}</p>
        </div>
        <h2>Task Breakdown</h2>
        <table>
          <thead>
            <tr>
              <th>Task Name</th>
              <th>Project</th>
              <th>Hours</th>
              <th>Date Range</th>
            </tr>
          </thead>
          <tbody>
            ${tasksList}
          </tbody>
        </table>
        <p style="margin-top: 30px; color: #6b7280; font-size: 0.875rem;">
          Generated by Time Management System
        </p>
      </div>
    </body>
    </html>
  `;
};

